### ISSUE TITLE
Internal Server Error on Image View on Docker 1.4.1

### ISSUE THREAD

**Issue by ycprog** [atc-/docker-registry-web#121]
I'm having this error when viewing images push and built from docker 1.4.x. Not sure if the latest version of the docker is the cause of it, but images pushed from previous version (1.3.x) before the upgrade seems to work. I'm running 0.96.0 inside a docker container.

Error 500: Internal Server Error
URI
/repository/show
Class
groovy.lang.MissingPropertyException
Message
No such property: checksum for class: docker.registry.web.support.Image
Trace
    Line | Method
->>   87 | doCall              in docker.registry.web.RepositoryService$_tt__getImageDetail_closure12_closure19
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    508 | doRequest           in groovyx.net.http.HTTPBuilder
|    441 | doRequest . . . . . in     ''
|    390 | request             in     ''
|     84 | $tt__getImageDetail in docker.registry.web.RepositoryService
|     23 | doCall              in docker.registry.web.RepositoryService$_$tt__detail_closure9
|     21 | $tt__detail . . . . in docker.registry.web.RepositoryService
|     22 | show                in docker.registry.web.RepositoryController
|    198 | doFilter . . . . .  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter            in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter . . . . .  in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     49 | doFilter            in grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter
|     82 | doFilter . . . . .  in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|   1145 | runWorker           in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                 in java.lang.Thread

**Comment by templefox** [comment]
I meet the same issue. Any idea?

**Comment by atc-** [comment]
I think something in the registry API has changed. What versions of Docker Registry are you using?

**Comment by atc-** [comment]
Should now be resolved in version 0.96.1.

**Comment by atc-** [comment]
Please re-open if this is an issue in the latest release of docker-registry-web

**Comment by manuelmazzuola** [comment]
Docker 1.5.1 and latest docker-registry-ui image

```
URI
/repository/show
Class
java.lang.NullPointerException
Message
Cannot set property 'displayName' on null object
```

```
    Line | Method
->>   27 | doCall      in docker.registry.web.RepositoryService$_$tt__detail_closure9
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     24 | $tt__detail in docker.registry.web.RepositoryService
|     22 | show . . .  in docker.registry.web.RepositoryController
|    198 | doFilter    in grails.plugin.cache.web.filter.PageFragmentCachingFilter
|     63 | doFilter .  in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter    in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     49 | doFilter .  in grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter
|     82 | doFilter    in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|   1145 | runWorker . in java.util.concurrent.ThreadPoolExecutor
|    615 | run         in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . in java.lang.Thread
```
