### ISSUE TITLE
show image message in image description or extra segment

### ISSUE THREAD

**Issue by larrycai** [atc-/docker-registry-web#123]
I use `docker commit --message <message>` to store some comments into the image.

How I can see this information in image detail information page ?

Which information is supposed to be shown in "Description" section in detail information page ?

**Comment by atc-** [comment]
I'm not sure if this is visible via the docker registry's API -- it doesn't seem to mention it in the documentation.

As for the description, I believe this might actually be specific to docker hub as I cannot see a means of setting a description via the API or docker documentation.

**Comment by larrycai** [comment]
I agree, probably we need to push for later release for docker registry API
to contain more information.

We can do nothing here.

On Sun, Jan 4, 2015 at 7:23 PM, Alex Collins <notifications@github.com>
wrote:

> I'm not sure if this is visible via the docker registry's API -- it
> doesn't seem to mention it in the documentation.
>
> As for the description, I believe this might actually be specific to
> docker hub as I cannot see a means of setting a description via the API or
> docker documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/atc-/docker-registry-web/issues/123#issuecomment-68629512>
> .
>



-- 
True software development embraces consistent inconsistency.
blog: http://larrycaiyu.com/blog (en), http://larrycaiyu.com (chinese)
