### ISSUE TITLE
Tomcat7 is not starting

### ISSUE THREAD

**Issue by mokriy** [atc-/docker-registry-web#127]
Hi, 
On Ubuntu 14.04
having:
sudo docker run -p 8080:8080 atcol/docker-registry-ui
causes the following trace:

Jan 14, 2015 5:58:39 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 14, 2015 5:58:39 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/common], exists: [false], isDirectory: [false], canRead: [false]
Jan 14, 2015 5:58:39 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 14, 2015 5:58:39 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/server], exists: [false], isDirectory: [false], canRead: [false]
Jan 14, 2015 5:58:39 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
Jan 14, 2015 5:58:39 PM org.apache.catalina.startup.ClassLoaderFactory validateFile
WARNING: Problem with directory [/usr/share/tomcat7/shared], exists: [false], isDirectory: [false], canRead: [false]
Jan 14, 2015 5:58:40 PM org.apache.catalina.startup.Catalina initDirs
SEVERE: Cannot find specified temporary folder at /var/lib/tomcat7/temp
Jan 14, 2015 5:58:41 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Jan 14, 2015 5:58:41 PM org.apache.catalina.startup.Catalina load
INFO: Initialization processed in 1782 ms
Jan 14, 2015 5:58:42 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Catalina
Jan 14, 2015 5:58:42 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.52 (Ubuntu)
Jan 14, 2015 5:58:42 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deploying web application archive /var/lib/tomcat7/webapps/ROOT.war
Killed

So, the container does not start.
Thanks in advance!
Alex

**Comment by atc-** [comment]
Do you kill the container? What version of docker the this app?

**Comment by mokriy** [comment]
No I did not. It happens every time I try to run container.
docker -version
Client version: 1.4.1
Client API version: 1.16
Server version: 1.4.1
Server API version: 1.16

Could it be that OS sends SIG if container exceeds available VM?

**Comment by mokriy** [comment]
I have extended RAM on VirtualBox and it works, sorry!)
