### ISSUE TITLE
Configuration Issue: ping failed

### ISSUE THREAD

**Issue by LennyBasuino** [atc-/docker-registry-web#132]
Hoping you can help with the following error:

Ping failed: java.net.NoRouteToHostException: No route to host

I'm using docker registry server 0.9.1 and docker registry web 0.9.5.

The web output looks like this:

INFO conf.Bootstarp - Checking for registry in system env
INFO conf.BootStrap - Found registry http://myhost.mydomain.net:8000/v1/. Creating...
INFO - conf.BootStrap - Registry Registry{id=null, protocol='http', host=''myhost.mydomain.net', port=8000, apiVersion='v1', username='null', password='null', repositoryService=docker.registry.web.RepositoryService@11bb4497, version=null} doesn't exist; saving
INFO web.RepositoryService - Ping failed: java.net.NoRouteToHostException: No route to host
WARN - conf.BootStrap = Registry 'http://myhost.mydomain.net:8000/v1' ping failed! Check it;s up!

TIA!
Lenny B.

**Comment by atc-** [comment]
I suspect your container can't see the host "myhost.mydomain.net". What docker version are you using? Latter versions of Docker allow you write to `/etc/hosts`which is what you could use to set the hostname internally to the container allowing it to see the registry.

Other alternatives are dnsmasq etc on the host. Hope that helps.

**Comment by LennyBasuino** [comment]
I'm using Docker 1.4.1.

**Comment by atc-** [comment]
Can you paste the parameters you use to start the docker-registry-web container please?

**Comment by LennyBasuino** [comment]
The params for the docker-registry-web container are:

docker run -p 8080:8080 -e REG1=http://myhost.mydomain.net:8000/v1/ -v /opt/data/docker/registry_web atcol/docker-registry-ui

Other docker processes of interest (ps -ef | grep docker):

docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 8080 -container-ip 172.17.0.2 -container-port 8080

and there are 5 of these processes:

/usr/bin/python /usr/bin/gunicorn --access-logfile --error-logfile - --max-requests 100 -k gevent --graceful-timeout 3600 -t 3600 -w 4 -b 0.0.0.0:8000 --reload docker_registry.wsgi:application

TIA!

**Comment by atc-** [comment]
If you do a `docker run` of the docker-registry-ui and pass `/bin/bash` as the last argument to get a shell, are you able to `ping` that same hostname?

**Comment by LennyBasuino** [comment]
I added --insecure-registry as per http://stackoverflow.com/questions/26710153/remote-access-to-a-private-docker-registry , but still having a problem.

I'm not familiar enough with docker to know I am doing what you asked, so let me describe it in detail ...

The "docker run" command needs an IMAGE, so I ran "docker ps" to get the IMAGE name and then:

docker run atcol.docker-registry-ui:latest /bin/bash

it returns but I don't believe it entered a new shell, because a Ctrl-D exits me out of the original shell.
The ping did return successfully, but I don't believe it was executed from within the container.

**Comment by atc-** [comment]
The thing I'm trying to answer is: can the docker-registry-ui container see the registry host via the given hostname, across the network?

**Comment by LennyBasuino** [comment]
OK, this did run and ping succeeded:

docker run atcol.docker-registry-ui:latest /bin/ping myhost.mydomain.net

**Comment by LennyBasuino** [comment]
Another data point (now that I know how to use docker run) ...

I have another docker registry server (older version) that is working ...

docker run atcol.docker-registry-ui:latest /usr/bin/curl http://oldhost.mydomain.net:8000/_ping

succeedes

but

docker run atcol.docker-registry-ui:latest /usr/bin/curl http://myhost.mydomain.net:8000/_ping

fails with "No route to host"

**Comment by atc-** [comment]
Perfect, you got it :) That's what I wanted to test with eventually.

Is the registry *actually* running on myhost? Can you curl and get a good response from your main machine (i.e. not a container)?

**Comment by LennyBasuino** [comment]
Yes, curl from the main machine succeeds.

curl http://myhost.mydomain.net:8000/_ping

**Comment by atc-** [comment]
When you view the image list through docker-registry-ui can you actually see the images?

**Comment by LennyBasuino** [comment]
Yes (docker images).  Well at this point there is only 1 image, atcol/docker-registry-ui.  The browser can connect to the running container, but it appears the container is failing to ping the registry server.  BTW, they are running on the same machine.

**Comment by atc-** [comment]
What IP is the hostname of the registry that the container uses?

**Comment by LennyBasuino** [comment]
I don't know how to connect to the running container.  Using the "docker run" command with "cat /etc/hosts" shows the ip of the container changes from run to run

docker run atcol.docker-registry-ui:latest cat /etc/hosts

172.17.0.36
172.17.0.37
172.17.0.38
...

**Comment by atc-** [comment]
What IP will myhost.mydomain.net resolve to inside the container? If it's on the host, it needs to resolve to `172.17.42.1`.

**Comment by LennyBasuino** [comment]
Ok ... to find the container id:

docker ps

With the ID:

docker exec <ID> cat /etc/hosts

it shows IP of 172.17.0.2

**Comment by atc-** [comment]
So, as if I've understood you right, your registry's hostname resolves to `172.17.0.2` inside the container and this is the problem -- it's resolving to the subnet of the container and not "routing" outside to the host.

**Comment by atc-** [comment]
Also can you update docker-registry-ui? You're on quite an old version now.

**Comment by LennyBasuino** [comment]
Is there a way I can provide the ip for the container to use?

I'll also persue updating the docker-registry-ui (which for reasons beyond my control, will take some time ... it is what it is)

**Comment by LennyBasuino** [comment]
I need to correct a misunderstanding on the IP addresses.

I got the container ID from "docker ps".

docker exec ID /bin/ping myhost.mydomain.net

returns a successful ping and the correct IP.

docker exec ID cat /etc/hosts

returns 172.17.0.2 as the ip of ID.  This is further confirmed by:

docker exec ID /bin/ping ID

which returns successful pings with IP 172.17.0.2


So if the container needs to be 172.17.42.1 I have something misconfigured.  How to I force that IP for the docker-registry-ui container?

**Comment by atc-** [comment]
If the registry is running on the host that'll run the container, then your the IP in the container for your registry needs to be, or map to, `172.17.42.1` (the host's IP).

**Comment by atc-** [comment]
Did this help, @LennyBasuino ?

**Comment by LennyBasuino** [comment]
@atc- thanks you for your time and the information.  I better understand how to debug this further.  I'll post when I have this working; may be a while as I got pulled off onto other things.  Thanks again!

**Comment by LennyBasuino** [comment]
@atc- It turned out to be a configuration setting on my Registry Server that was blocking the Docker Registry Web.  The application is working splendedly.  Thanks again!

**Comment by atc-** [comment]
Yay glad it's working; happy to help!

**Comment by namik-hajiyev** [comment]
@LennyBasuino could you tell what part of the configuration was causing the problem ? I am experiencing the same issue.
