### ISSUE TITLE
Registry can't find all images in the repository

### ISSUE THREAD

**Issue by alexfvolk** [atc-/docker-registry-web#133]
Hi, 

I think I know why that happens, docker registry container loses the records of what was pushed to the repo, I wish search was done against the backend directly (in my case I use s3 bucket). I have a cloud template, so I start my stack from scratch very often, downloading the registry container over again, setting up all the configs, of course I lose all the data of the images I pushed to the repo. That in turn means that the web ui also cannot find any images which is a real drawback, because s3 might be persistent, but my docker registry ec2 instance can be updated or go down for any reason and a brand new one will be spun up by an autoscaling group.

So my question is basically, what is the best available way to always connect to a registry and always see all images in the s3 repo, whether registry was rebooted or a new one was spun up? Mounting a volume from ec2 instance won't work because it is very possible it could be go down for whatever reason and have a new one spin up.

**Comment by atc-** [comment]
This web app makes no "local record" of the images -- everything you see on the web UI is read straight from the REST API from the registries it's configured to talk to. If you're not seeing it on the UI then it's likely the registry is misbehaving.

**Comment by atc-** [comment]
Is your issue resolved?
